services:
  web:
    build: .
    ports:
      - "3005:3005"
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - WASP_WEB_CLIENT_URL=${WASP_WEB_CLIENT_URL}
      - WASP_SERVER_URL=${WASP_SERVER_URL}
    restart: always
